ARG BASE_CONTAINER=jupyter/tensorflow-notebook
FROM $BASE_CONTAINER

LABEL maintainer="objective partner AG - KAM Community"
COPY ./weatherproject /home/$NB_USER/work

WORKDIR /home/$NB_USER/work

# Install Tensorflow
RUN pip install --quiet -r requirements.txt

USER root
